In [5]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [10]:
x = np.arange(6).reshape(3,2)

In [11]:
degree = 2

poly_transform = PolynomialFeatures(degree=degree)

In [12]:
new_features = poly_transform.fit_transform(x)

In [14]:
new_features.shape

(3, 6)

# split line

In [18]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

In [20]:
model = Pipeline([("poly",PolynomialFeatures(degree=3)),
                  ("linear",LinearRegression(fit_intercept=False))])

In [23]:
x = np.arange(5)
y = 3-2*x+x**2-x**3

In [26]:
print("x:{}".format(x))
print("y:{}".format(y))

x:[0 1 2 3 4]
y:[  3   1  -5 -21 -53]


In [27]:
model = model.fit(x[:,np.newaxis],y)

In [28]:
model.named_steps["linear"].coef_

array([ 3., -2.,  1., -1.])

In [29]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [30]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = x[:,0]^x[:,1]

In [31]:
print("x:{}".format(x))
print("y:{}".format(y))

x:[[0 0]
 [0 1]
 [1 0]
 [1 1]]
y:[0 1 1 0]


In [32]:
x = PolynomialFeatures(interaction_only=True).fit_transform(x).astype(int)

In [33]:
x

array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [36]:
clf = Perceptron(fit_intercept=False,
                max_iter=10,
                tol=None,
                shuffle=False).fit(x,y)

In [37]:
clf

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=False, max_iter=10, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=False, tol=None,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [38]:
clf.predict(x)

array([0, 1, 1, 0])

In [39]:
clf.score(x,y)

1.0